services:
  - type: web
    name: pruebas-render-github-n8n
    env: node
    plan: free
    buildCommand: npm install && npx puppeteer browsers install chrome
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
